### ISSUE TITLE
Feature: learn a call, and you know it everywhere? OR I only call it if ALL clubs have taught it?

### ISSUE THREAD

**Issue by mpogue2** [mpogue2/SquareDesk#118]
Dan, I really like the changes in 8be0b1033f5ace583a1c5a3a7afcba4ca3f23bcf !

One suggestion: I made my own test dance program, "Mike's Dance Program", and it had only the first 4 calls from Basic 1 in it.  If I check off those calls, which (and this is important) are identical to calls on the Basic 1 list, my hope was that would check them off on ALL of the dance programs.

This way, we could also have a GDP list, or a "January class list", and just by adding it, the calls would be already populated correctly for ALL lists, by checking them off on ANY list.  I'll send you the checklist that the local clubs use, as an example of something that is close.

One disadvantage is that you then couldn't have separate lists for separate classes.  
This could also be fixed with metadata, e.g. the first line of a dance program contains a key (maybe called a "dance program group"?), and all lists containing the same key are linked.  And, the key is not shown in the Dance Programs tab.  Alternately, this could be done by file naming convention, e.g. <num>.<danceprogramname>.<danceprogramgroup>.txt, or by sticking groups of them in folders.

Alternately, (and this is just the OPPOSITE of what I just proposed) each of the lists could literally be separate clubs, and the user can select individual clubs using the current pulldown menu.  BUT, if there's an additional "GROUP" list, it would show as checked off ONLY those calls that were checked off by ALL clubs in the group.  This also opens up the ability to fetch the club lists via URL!
I happen to need this for my dance next month, which is Jan Class Level for 3 clubs (the intersection of them all).

I suppose both could also be implemented at the same time, using both filenames and folders, or more .tag. style tags....  But this might start to get confusing?

Anyway, some thoughts.  I like it so far!  Lots of interesting possibilities.

**Comment by danlyke** [comment]
So it'd be easy enough to drop the list from the key in the database.
We still have the session differences to track teaching separate
classes on the same night.

Or, as you propose, we could add metadata in the lists file that let us
say "by the way, this list works with this other list".

An application: Teaching Club 50 and then teaching full Plus, and you'd
want the full plus list to reflect the Club 50.

So, yeah: Something like a line in the file that says:

  Same as: plus

or

  Shared program: plus

Or something like that?

**Comment by mpogue2** [comment]
That would certainly work.  My bias is toward configuration by naming or by placement, instead of by an extra line added to the file, just because editing a file (correctly) is more error prone in my experience.  But, they are all semantically equivalent, so any would technically work.

I'm curious though -- which of these opposite ideas fits your current way of working?
a) two dance programs, and when you check a call off in one, they all get checked off (e.g. square thru was taught, so it was taught for MS and for Club50), and then you can search for sequences by either MS or Club50 (but not both), or
b) two clubs (sessions), and there's a MS list for each one, and then you can search for sequences by either MS (club 1) or MS (club 2), but not both?
c) Two clubs and each club has a selected dance program, and each is completely separate?

**Comment by danlyke** [comment]
My notion is c; All dance programs are completely separate. But I envision that separation happening mostly through sessions.

I can see an argument for a; the "when we're done with Club 50 we go on to full Plus, but want to see what we've taught from Club 50 already checked off".

I think you've made a good case for "sortorder.programgroup.danceprogram.txt" (less than greater than tags left out because they don't render in the HTML view of the issue...)

Maybe make sortorder required to be numeric, and then sortorder and programgroup can be optional.

So someone wanting to set up a "club50" that sorted at the end could rename our example files and add a new one as:

010.bmsp.basic1.txt
020.bmsp.basic2.txt
030.bmsp.mainstream.txt
040.bmsp.plus.txt
050.a1.txt
060.a2.txt
bmsp.club50.txt

And this would give us a "club50" that'd check off of the bmsp list, and would sort after the others. (And, whoops, apparently I missed mainstream in my original, added in abafca307acc6a9e6abf794c93da77574b32ea3f, delete your .txt files to regenerate them. Doh.)

I'll try to code this up...

**Comment by mpogue2** [comment]
OK, cool...I'm thinking of the use case when we will want to say "show me all the sequences that can be called at the January-class-level dance on Friday", where "January-class-level dance on Friday" = some subset of the BMSP list that is specific to this particular dance.  If I understand you correctly, I think this is possible, but I'm not sure exactly what UI actions I would need to do to make this happen.
Do I need to make a new custom session?  Or, do you foresee some search box that let's me check off the dance programs (and sessions?) that are merged?

**Comment by danlyke** [comment]
This will be possible after I finish implementing your
sortorder.programname.callsinprogram.txt suggestion.

I'm splitting my energies this afternoon between helping Charlene write
an angry letter to upper management and coding on SquareDesk, so there
is a bit of "hey, I've just printed this out, go proofread it and mark
it up" going on here...

Dan

**Comment by danlyke** [comment]
Okay 2021e5ed0786f3b00cc519b811cab2326972193f which is the head of the
danlyke branch, allows 2 or 3 part names.

In the "reference" directory of my music folder, I did:

`mv 010.basic1.txt 010.bms.basic1.txt`
`mv 020.basic2.txt 020.bms.basic2.txt`
`mv 030.mainstream.txt 030.bms.mainstream.txt`
`cat *.bms.*.txt > bms.txt` 

This created a "bms" dance program that had all of the calls from
basic1, basic2, and mainstream. Showed up in the database as "bms", let
me set and clear from those two.

`mv bms.txt 005.bms.txt` to move it to the top of the sort order also
worked.

Final question: Given that we're using every .txt file in the
"reference" directory as a list, do we need some more smarts or
restriction on naming format?

**Comment by danlyke** [comment]
I'm ready to merge this back into the main branch if we decide yay or nay on "every text file inside resources/ is a call program", or if we want a little more restriction than that.

**Comment by danlyke** [comment]
Oh and, d35f6c0b1057741e688d991268e3908c8659f249 fixes the truncated Plus list. Doh.

**Comment by mpogue2** [comment]
After the latest commit (3b509d9398dec774c48877a6f3aca908de638dd8), I see no Ages at all (I'm on Practice).  All my previous data on Age seems to be missing (blank).  Clicking on Session > Show All Ages shows a bunch of ages (which I suspect are correct), but it takes about 5 seconds to select that option or to turn it off.  

In Dance Programs, every single call is checked off on all lists.  If it wasn't checked off before, it is now, with a date of today.

So, I don't think either of these features is quite ready yet...

**Comment by mpogue2** [comment]
Couple more:
danceprograms.h was not included in the project (I'm not sure why not!)
line 2 of danceprograms.h has too many D's. (generates warning, but this is a minor bug)
line 3258 of mainwindow.cpp generates a warning that the "!" applies to the length() call, and not to the entire expression.  So, this is a minor bug -- it probably doesn't do what you meant...

**Comment by danlyke** [comment]
Aaargh! Somehow I fouled up a thing that I thought was related to the
session handling and ages, and ended up making an "auto check
everything" bug for the call list.

70e3d43e747c1810aaab82bc2b5557163f58538f should have those things
fixed, *and* should speed up the loading of the song ages by a little
bit. If this is still taking 5 seconds on your machine then I need to
do a little more profiling (which is hard on something that only runs
for 5 seconds). It was probably taking a second or two on my machine,
now it's faster, but I suspect that turning off and on the sort stuff
(incidentally, it's a bad idea to reference things by row index with the
sort turned on, as I discovered...) is where the speed is going right
now.

**Comment by mpogue2** [comment]
In Top of DanLyke Tree:
danceprograms.h fixed
Ages back to normal -- yay!
! fixed

New bug (or recurrence of an old bug?): I opened Another Saturday Night (which has embedded ID3 lyrics), and then switched to Lousiana Saturday Night (Low Key), and the Lyrics pane shows the correct file path in the dropdown for Louisiana Saturday Night lyrics (and that file DOES contain the lyrics for Louisian Saturday Night), but the actual lyrics showing is from Another Saturday Night (embedded), which is not an option on the dropdown list....I'll attach a picture.
<img width="400" alt="bug_lyrics" src="https://cloud.githubusercontent.com/assets/6316003/26475261/8561ccb6-416b-11e7-901e-8ce642f7e839.png">

**Comment by mpogue2** [comment]
Couple other things I noticed:
1) Because of the previous bug, everything is checked.  I think this argues for some way to clear
them all (like at the beginning of a teaching season)
2) Should the program level dropdown menu selection be persistent?  I sort of expected that it would be, and was a little surprised when I had to reselect the program level each time I came into the app.
3) All of the checkboxes are grey, until I change the state of one of them.  Then, ALL of the checked boxes turn bright blue, but they all go back to grey WHILE I am selecting a new program level, and when the new program level shows up, they all go bright blue again.  All back to grey after an app restart.  Maybe something with the table containing them having focus?  I'm not sure how focus should work on this page.

Other than that, the program level stuff seems to be working.  I haven't tried the grouping thing yet...

**Comment by danlyke** [comment]
-1. Huh, okay, I need to go back and review how the in-MP3 lyrics stuff is getting handled, because presumably that's the issue.

1. Yes, in fact I have the API in there, I just need to wire up a button. Presumably with a "are you sure?" dialog.
2. Yes. We should fix this.
3. I have no idea. Don't see that behavior on Linux. I think your hypothesis about focus is a good one.

**Comment by mpogue2** [comment]
-1.  yeah, I thought this was fixed before...but it's baaaa-aaack.
1. sounds good, since it's a lot of data, and there's no undo.
2. sounds good.
3. I'm pretty sure it's focus.  What should be the focus policy on this page?  I dunno...it looks like I can select individual calls, too, and they turn blue, too.  Should I be able to move focus with TAB?  Inquiring minds want to know... :-)
Not blue:
<img width="1008" alt="screenshot 2017-05-25 17 17 16" src="https://cloud.githubusercontent.com/assets/6316003/26475725/51481ef0-416e-11e7-9835-2ef24974ce82.png">
Blue, if I click in the table:
<img width="1008" alt="screenshot 2017-05-25 17 17 50" src="https://cloud.githubusercontent.com/assets/6316003/26475729/5d3647dc-416e-11e7-8c60-4247f1571e7f.png">

**Comment by mpogue2** [comment]
Extremely blue, if I click on a call:
<img width="1008" alt="screenshot 2017-05-25 17 21 59" src="https://cloud.githubusercontent.com/assets/6316003/26475781/c18775e4-416e-11e7-9549-09b0d52809c8.png">

I think there's a QT Designer way to turn off accepting focus.  Somewhere.

**Comment by mpogue2** [comment]
re: -1, I think I sent you a file that has embedded lyrics in it, so should be reproducible...

**Comment by danlyke** [comment]
On the wrong cuesheet showing up: In loadCuesheet(), can you put in a `qDebug() << cuesheetFilename;` and see what it's trying to load?

**Comment by danlyke** [comment]
There's a "focusPolicy" attribute, I set it from the default "wheelFocus" to "noFocus". I'm still able to highlight lines, but I'm still not getting the bright blue around the checkboxes.

**Comment by mpogue2** [comment]
Here's the qDebug() output.  
loadCuesheet() "/Users/mpogue/__squareDanceMusic/test/RR 212 - Another Saturday Night.mp3"
loadCuesheet() "/Users/mpogue/__squareDanceMusic/test/RR 212 - Another Saturday Night.mp3"
loadCuesheet() ""
loadCuesheet() "/Users/mpogue/__squareDanceMusic/lyrics/SqViewCueSheets-9-30-16 Text/C 0311 - Louisiana Saturday Night.html"
loadCuesheet() "/Users/mpogue/__squareDanceMusic/lyrics/SqViewCueSheets-9-30-16 Text/C 0311 - Louisiana Saturday Night.html"
loadCuesheet() ""
loadCuesheet() "/Users/mpogue/__squareDanceMusic/test/RR 212 - Another Saturday Night.mp3"
loadCuesheet() "/Users/mpogue/__squareDanceMusic/test/RR 212 - Another Saturday Night.mp3"
loadCuesheet() ""
loadCuesheet() "/Users/mpogue/__squareDanceMusic/lyrics/SqViewCueSheets-9-30-16 Text/C 0311 - Louisiana Saturday Night.html"
loadCuesheet() "/Users/mpogue/__squareDanceMusic/lyrics/SqViewCueSheets-9-30-16 Text/C 0311 - Louisiana Saturday Night.html"

To reproduce: start the app, search for "Satur", 
a) double click Another Saturday Night, click Lyrics (it's correct), click Music Player, 
b) double click Louisiana Saturday Night (called), click Lyrics (it's correct), click Music Player,
c) repeat step a (it's correct)
d) repeat step b (it's now wrong, showing lyrics for step a but I'm viewing step b's song.

**Comment by mpogue2** [comment]
Step a) creates two loadCuesheet() debug lines.  Steps b, c, and d) all create three loadCuesheet() debug lines...HTH

**Comment by danlyke** [comment]
Hmmm... We can probably do something about the large number of reloads...

If it says it's loading "/Users/mpogue/__squareDanceMusic/lyrics/SqViewCueSheets-9-30-16 Text/C 0311 - Louisiana Saturday Night.html", I have no idea why it'd be showing the cue sheet for "/Users/mpogue/__squareDanceMusic/test/RR 212 - Another Saturday Night.mp3" unless there's some untrapped error that we're not seeing with the load of the latter.

The code path for anything ending in .html is pretty simple, just create a URL and set the control source to that URL.

**Comment by danlyke** [comment]
02288d1a0e83dbbde442fbe66b291134ac2beaea fixes the remembering the last dance program problem.

**Comment by danlyke** [comment]
And 5f4436deddff0a74b1eaabea7d4611e35497aaad adds a "clear all checkmarks" button.

**Comment by danlyke** [comment]
And I'm having no luck reproducing the cuesheet problem.

**Comment by mpogue2** [comment]
I'll try to reproduce the cue sheet problem better.
Other changes look good...

More small/minor things (sorry for reporting these in dribs and drabs -- I'm seeing a couple new ones each time I play with it, but they're definitely getting smaller):
a) checkboxes should be centered in the check column (and maybe it needs a couple more pixels of width?), like the header
b) row numbers should be removed, I think.  The "Teach" field is really the row number.
c) The checkbox column is not currently sortable.  Ideally, it should be made actually sortable, or the sorting triangles when clicking on the header should be disabled.  I guess I am mildly in favor of making them sortable (but either would be fine).
d) Completed date column contents should be centered (like the header).

Other:
e) Nice-to-have: it would be nice for all the text to use the same sizes as in the Music Player (the font stuff that was recently added)...note that auto-column sizing might need to be turned off and then back on again, to improve performance, like is done for songTable
f) Nice-to-have (I'll probably work on this if you don't have time): the Flash Calls feature should choose calls that are checked from one of the dance program lists or virtual groups.  So, the Flash Calls feature needs a dropdown for the Dance Programs in the Experimental Preferences  page.  This is under the category of "integrating the pieces to work together", which I think is very cool when we can do it.
g) SD could use these lists for deciding what level is allowed...(later)

**Comment by mpogue2** [comment]
re: Another Saturday Night...it's not picking up an external cue sheet, it's picking up the USLT ID3 tag.  Sorry if I didn't say that clearly before... loadCuesheet is only for .txt/.htm/.html, right?

Also, I am going to pull the performance problem with Show All Ages out to a new Issue.  It takes ~5 seconds of beach ball to go in and out of that mode.

**Comment by mpogue2** [comment]
OK, I think I fixed the ID3 vs HTML cue sheet problem, but I admit I'm not 100% sure I understand WHY this change fixed it.  I noticed that on_comboBoxCuesheetSelector_currentIndexChanged() was being called with -1, which presumably means "not anything is selected", but we called loadCuesheet anyway.  I put a guard around that call, so that if it's -1, we do NOT call loadCuesheet.  And, the problem went away.  It was 100% repeatable before, now 0% repeatable.  But, I'm not sure why this worked, because the cuesheet Filename was the correct one.  Maybe some weird interaction between loading the pane with TEXT vs HTML/URL?  My next attempt was going to clear both the TEXT and the HTML before loading a cue sheet.  But, I'll hold off on that for now.

**Comment by mpogue2** [comment]
I opened #122 to cover the ID3 vs HTML cue sheet problem, and I checked in a fix into the DanLyke branch.  Please try it, and let me know if it messes anything up for you.  It fixed the problem 100% for me.

**Comment by danlyke** [comment]
On Thu, 25 May 2017 20:34:58 -0700
Mike Pogue <notifications@github.com> wrote:
> re: Another Saturday Night...it's not picking up an external cue
> sheet, it's picking up the USLT ID3 tag.  Sorry if I didn't say that
> clearly before... loadCuesheet is only for .txt/.htm/.html, right?

No, loadCuesheet looks for extensions: For ".mp3" it does the ID3 load,
for ".txt" it does an internal formatting to HTML, for everything else
it loads it as HTML.

> Also, I am going to pull the performance problem with Show All Ages
> out to a new Issue.  It takes ~5 seconds of beach ball to go in and
> out of that mode.

That is totally bizarre. It takes a little longer than it should here,
but that's like a second or two. And commenting out the database load
doesn't make it any faster, so it appears to be turning off and on the
sorting on the view.

Dan

**Comment by danlyke** [comment]
So I think the remaining issue here is the blue when a control gets highlighted?

**Comment by mpogue2** [comment]
Ummm...I think so, but I'd have to go over each of the comments in detail...
