### ISSUE TITLE
Feature: Open M3U Playlists from Apple Music in SquareDesk, or access them directly

### ISSUE THREAD

**Issue by paddyboehnke** [mpogue2/SquareDesk#1268]
Hi, 
I'm new to version 1.0.15 - I had 0.9.5 installed and running for quite some time.
My workflow is that I organise my music in pApple Music playlists and then export them as  .m3u file so I can open them in SD.
The new version doesn't read any m3u files (or any other format that Apple Music can export to).
Are you planning to work on this?

Thanks, Paddy

**Comment by mpogue2** [comment]
I actually removed the m3u support a while ago, because nobody was using it!

I am actually thinking to support this use case in a different way, and I'd like your opinion:

- In the left hand "tree view", it currently shows Tracks (your songs, organized into folders) and Playlists (CSV format playlists, organized hierarchically).
- I was thinking that we could access the Apple Music playlists directly, and create a new category at the same level as Tracks and Playlists, called "Apple Music".  
- Under that category, it would show all of the Apple Music playlists that you had
- and if you right-click on one of those playlists, you could show that playlist in one of the 3 "palette slots" in the middle of the screen.
- You can then double-click on songs in that palette slot to load them, just like one of the CSV-based playlists in the Playlists section.

What do you think?

In this approach, you don't need to export M3U files at all (or remember where you put those, so you can import them into SquareDesk).  Instead, you'd just make a playlist in Apple Music, and then load it directly into a palette slot later on in SquareDesk's Tree View.

Example of the current Tree View, showing hierarchical Playlists section:

<img width="243" alt="Image" src="https://github.com/user-attachments/assets/388be3e6-4980-4993-bfb3-20aab4299041" />

**Comment by pkbott** [comment]
I like this idea

**Comment by mpogue2** [comment]
@pkbott Are you also a user of Apple Music to organize your music?  If so, what's your workflow look like?  

I know there are a couple of callers out there who use Apple Music for square dance audio, but they tend to stick with Apple Music (MacOS) or something like AnyTune (iOS/iPadOS), rather than using something like SquareDesk.

**Comment by pkbott** [comment]
I don’t but liked the idea since that could be a music backup potentially

**Comment by mpogue2** [comment]
Note to self: see #1095 .  I just posted there an OSA script to fetch all of the local playlists.

**Comment by mpogue2** [comment]
@paddyboehnke @pkbott  OK, I had some time this evening, so I implemented a prototype of this.  Here's what it looks like (click the speaker icon to turn on the sound -- yes, this works for real... :-):

https://github.com/user-attachments/assets/04a2d656-44a8-4e41-99b4-fd86e0aafa3a

Steps:
- You have to have Apple Music up and running when you start SquareDesk (maybe I can eliminate this restriction later? I'm not sure...)
- In the Tree View, open up Apple Music.  These are all the user-created playlists that Apple Music knows about, that have 1 or more songs in them.
- Right-click on an Apple Music playlist, and tell it to load to a palette slot.
- You can now double click on songs in the palette slot to load them for playback.
- Right-click on the title bar of the palette slot, and choose Save 'Untitled playlist" to..., to save it as a CSV file.  If you forget to save the CSV file, and you close SquareDesk, it will prompt you to Save or Discard the CSV file.
- If you double-click load a file from that palette slot, when you change pitch and tempo, these will be remembered in the CSV file.
- Note: That CSV file (assuming you saved it somewhere in the playlist folder in the musicDirectory) will be remembered and loaded into that same slot next time you open SquareDesk.

**Comment by mpogue2** [comment]
Commit: 9582c1e661658a6703732adad2820b68b04e27b1

It used to be that M3U was the only export format that Apple Music did, that SquareDesk could import.  M3U support went away long ago, though.  So, this is a way, hopefully better, for importing from Apple Music.  It does require that Apple Music be running when SquareDesk is started (maybe I can eliminate that requirement at some future date).

**Comment by mpogue2** [comment]
@paddyboehnke I see what you're saying.  It would be more consistent to make it so that clicking in the Tree view (on anything) showed that thing in the main frame.  Right now (for historical reasons), sometimes it will change the main frame (if it's a Track filter), and sometimes it won't (if it's a playlist).

Let me think about this.  I like the idea of making it more consistent, and also easier to read!  But, I suspect that this change would not be simple to make, and I would have to think about how to implement it so that it works intuitively for all the controls (e.g. for the right-click menus to copy to a slot, or for the filter box to do additional filtering on a playlist).  In other words, there might be some other things that I'd have to do to make it work and be consistent overall.

But, generally, I am in support of making this change.

**Comment by kdg3sf** [comment]
Thanks, Mike! This will be a great help for us Apple Music users, and is similar to the way Anytune integrates with Apple Music. I'm a SquareDesk fan, though still not an actual user, but this might help me get one step closer. Adding it to your tree view was the right way to go.

I agree with @paddyboehnke that the more you can make all tree view elements behave consistently, the better, though this is already a huge step.

**Comment by mpogue2** [comment]
Thanks everybody for the comments!

I'm going to close this Issue, and open a new one that is the major change to make the Tree view more consistent.  It's over at #1274, if you want to follow along there. There are some interesting design challenges to work through (like how exactly should drag and drop work).
